import Head from 'next/head'
import Image from 'next/image'
import DonatorList from '../components/DonatorList'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Blood Donator Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
         {/* ====== Donator list ====== */}
          <DonatorList />

      </main>
    </div>
  )
}
