import Head from 'next/head'
import Image from 'next/image'
import  AllDonatorsByGroup from '../components/AllDonatorsByGroup'
import Eligible from '../components/Eligible'
import IndexTab from '../components/IndexTab'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Blood Donator Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
         {/* ====== Donator list ====== */}
         <IndexTab />
          {/* <Eligible />
          <AllDonatorsByGroup /> */}
      </main>
    </div>
  )
}
